# Copyright (C) 2008 Michael Vogt <michael.vogt@ubuntu.com>
# This file is distributed under the same license as the unattended-upgrades package.
# Hideki Yamane (Debian-JP) <henrich@debian.or.jp>, 2008.
# Takuma Yamada <tyamada@takumayamada.com>, 2016.
#
msgid ""
msgstr ""
"Project-Id-Version: unattended-upgrades 0.36debian1\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2015-07-02 12:27+0200\n"
"PO-Revision-Date: 2016-04-14 09:31+0900\n"
"Last-Translator: Takuma Yamada <tyamada@takumayamada.com>\n"
"Language-Team: Japanese <debian-japanese@lists.debian.org>\n"
"Language: ja\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=1; plural=0;\n"
"X-Generator: Gtranslator 2.91.6\n"

#: ../unattended-upgrade:162
#, python-format
msgid "Progress: %s %% (%s)"
msgstr "進行状況: %s %% (%s)"

#: ../unattended-upgrade:418 ../unattended-upgrade:501
#: ../unattended-upgrade-shutdown:161
msgid "All upgrades installed"
msgstr "全てのアップグレードがインストールされました"

#: ../unattended-upgrade:420 ../unattended-upgrade:493
msgid "Installing the upgrades failed!"
msgstr "アップグレードのインストールが失敗しました!"

#: ../unattended-upgrade:421 ../unattended-upgrade:494
#, python-format
msgid "error message: '%s'"
msgstr "エラーメッセージ: '%s'"

#: ../unattended-upgrade:422 ../unattended-upgrade:495
#, python-format
msgid "dpkg returned a error! See '%s' for details"
msgstr "dpkg がエラーを返しました! 詳細は '%s' を参照してください"

#: ../unattended-upgrade:795
msgid ""
"No '/usr/bin/mail' or '/usr/sbin/sendmail',can not send mail. You probably "
"want to install the 'mailx' package."
msgstr ""
"'/usr/bin/mail' または '/usr/sbin/sendmail' がないためメールを送信することが"
"できません。おそらく 'mailx' パッケージをインストールするとよいでしょう。"

#: ../unattended-upgrade:811
#, python-format
msgid "[reboot required] unattended-upgrades result for '%s': %s"
msgstr "[再起動が必要] '%s' の自動アップグレード結果: %s"

#: ../unattended-upgrade:814
#, python-format
msgid "unattended-upgrades result for '%s': '%s'"
msgstr "'%s' の自動アップグレード結果: '%s'"

#: ../unattended-upgrade:816
#, python-format
msgid ""
"Unattended upgrade returned: %s\n"
"\n"
msgstr ""
"自動アップグレードは以下を返しました: %s\n"
"\n"

#: ../unattended-upgrade:819
msgid ""
"Warning: A reboot is required to complete this upgrade.\n"
"\n"
msgstr ""
"警告: このアップグレードを完了するために再起動が必要です。\n"
"\n"

#: ../unattended-upgrade:821
msgid "Packages that were upgraded:\n"
msgstr "アップグレードされたパッケージ:\n"

#: ../unattended-upgrade:823
msgid "Packages that attempted to upgrade:\n"
msgstr "アップグレードしようとしたパッケージ:\n"

#: ../unattended-upgrade:827
msgid "Packages with upgradable origin but kept back:\n"
msgstr "導入元からアップグレード可能ですが、バージョンを維持したパッケージ:\n"

#: ../unattended-upgrade:832
msgid "Package installation log:"
msgstr "パッケージのインストールログ"

#: ../unattended-upgrade:835
msgid "Unattended-upgrades log:\n"
msgstr "Unattended-upgrades ログ:\n"

#: ../unattended-upgrade:855
#, python-format
msgid "Writing dpkg log to '%s'"
msgstr "dpkg のログを '%s' に書き込み中"

#: ../unattended-upgrade:987
#, python-format
msgid "Found %s, but not rebooting because %s is logged in."
msgid_plural "Found %s, but not rebooting because %s are logged in."
msgstr[0] "%s が見つかりましたが、%s がログインしているため再起動しません"

#: ../unattended-upgrade:1033
#, python-format
msgid "package '%s' upgradable but fails to be marked for upgrade (%s)"
msgstr ""
"パッケージ '%s' はアップグレード可能ですが、アップグレード予定にできませんで"
"した (%s)"

#: ../unattended-upgrade:1097
#, python-format
msgid "Packages that are auto removed: '%s'"
msgstr "自動削除されたパッケージ: '%s'"

#: ../unattended-upgrade:1103
msgid "Packages were successfully auto-removed"
msgstr "パッケージの自動削除が成功ました"

#: ../unattended-upgrade:1105
msgid "Auto-removing the packages failed!"
msgstr "パッケージの自動削除が失敗しました!"

#: ../unattended-upgrade:1106
#, python-format
msgid "Error message: '%s'"
msgstr "エラーメッセージ: '%s'"

#: ../unattended-upgrade:1107
#, python-format
msgid "dpkg returned an error! See '%s' for details"
msgstr "dpkg がエラーを返しました! 詳細は '%s' を参照してください"

#: ../unattended-upgrade:1125
#, python-format
msgid "Initial blacklisted packages: %s"
msgstr "初期状態でブラックリストにあるパッケージ: %s"

#: ../unattended-upgrade:1130
#, python-format
msgid "Initial whitelisted packages: %s"
msgstr "初期状態でホワイトリストにあるパッケージ: %s"

#: ../unattended-upgrade:1133
msgid "Starting unattended upgrades script"
msgstr "自動アップグレードスクリプトを開始します"

#: ../unattended-upgrade:1136
#, python-format
msgid "Allowed origins are: %s"
msgstr "許可されているパッケージ導入元: %s"

#: ../unattended-upgrade:1152 ../unattended-upgrade:1153
msgid "Unclean dpkg state detected, trying to correct"
msgstr "未消去の dpkg 状態が検出されたので、修正しようとしています"

#: ../unattended-upgrade:1164
#, python-format
msgid ""
"dpkg --configure -a output:\n"
"%s"
msgstr ""
"dpkg --configure -a output:\n"
"%s"

#: ../unattended-upgrade:1173
msgid "Lock could not be acquired (another package manager running?)"
msgstr "ロックが取得できませんでした (別のパッケージマネージャが実行中?)"

#: ../unattended-upgrade:1175
msgid "Cache lock can not be acquired, exiting"
msgstr "キャッシュロックが取得できないので終了します"

#: ../unattended-upgrade:1182 ../unattended-upgrade:1183
#: ../unattended-upgrade:1363 ../unattended-upgrade:1364
msgid "Cache has broken packages, exiting"
msgstr "キャッシュに壊れたパッケージがあるので終了します"

#: ../unattended-upgrade:1226
#, python-format
msgid "GetArchives() failed: '%s'"
msgstr "GetArchives() が失敗しました: '%s'"

#: ../unattended-upgrade:1236 ../unattended-upgrade:1237
#, python-format
msgid "An error occurred: '%s'"
msgstr "エラー発生: '%s'"

#: ../unattended-upgrade:1239 ../unattended-upgrade:1241
#, python-format
msgid "The URI '%s' failed to download, aborting"
msgstr "URI '%s' からダウンロード出来ないので中断します"

#: ../unattended-upgrade:1245
#, python-format
msgid "Download finished, but file '%s' not there?!?"
msgstr "ダウンロード完了、しかしファイル '%s' がありません?!?"

#: ../unattended-upgrade:1261 ../unattended-upgrade:1265
#, python-format
msgid "Package '%s' has conffile prompt and needs to be upgraded manually"
msgstr ""
"パッケージ '%s' には手動で確認とアップグレードが必要な設定ファイルがあります"

#: ../unattended-upgrade:1293
#, python-format
msgid "package '%s' not upgraded"
msgstr "パッケージ '%s' はアップグレードされませんでした"

#: ../unattended-upgrade:1311
msgid ""
"No packages found that can be upgraded unattended and no pending auto-"
"removals"
msgstr "自動更新可能なパッケージおよび保留中の自動削除が見つかりません"

#: ../unattended-upgrade:1337
#, python-format
msgid "Packages that will be upgraded: %s"
msgstr "アップグレード予定のパッケージ: %s"

#: ../unattended-upgrade:1406
msgid "print debug messages"
msgstr "デバッグメッセージを出力"

#: ../unattended-upgrade:1409
msgid "make apt/libapt print verbose debug messages"
msgstr "apt/libapt の詳細なデバッグメッセージを出力"

#: ../unattended-upgrade:1412
msgid "print info messages"
msgstr "情報メッセージを出力"

#: ../unattended-upgrade:1415
msgid "Simulation, download but do not install"
msgstr "シミュレーションで、ダウンロードをしますがインストールはしません"

#: ../unattended-upgrade:1418
msgid "Upgrade in minimal steps (and allow interrupting with SIGINT"
msgstr "最小限の手順でアップグレード (SIGINT で中断できます"

#: ../unattended-upgrade:1427
msgid "You need to be root to run this application"
msgstr "このアプリケーションは管理者権限で実行する必要があります"

#: ../unattended-upgrade-shutdown:72
msgid "Unattended-upgrade in progress during shutdown, sleeping for 5s"
msgstr "シャットダウン時に進行中の unattended-upgrade、5 秒間スリープします"

#: ../unattended-upgrade-shutdown:125
msgid "Running unattended-upgrades in shutdown mode"
msgstr "unattended-upgrades はシャットダウンモードで実行中です"

#: ../unattended-upgrade-shutdown:153
#, python-format
msgid "Giving up on lockfile after %s delay"
msgstr "%s 遅延後にロックファイルをあきらめます"

#~ msgid "pm.GetArchives() failed"
#~ msgstr "pm.GetArchives() が失敗しました"
